import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const otherFontFamily = localFont({
  src: '../../public/sans.woff',
  display: 'swap',
  variable: '--font-main',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={` ${otherFontFamily.variable} dark:bg-[hsl(var(--background))] bg-[hsl(var(--background-end-rgb))]`}>
      <body className="text-[hsl(var(--foreground))]">{children}</body>
    </html>
  );
}
